### ISSUE TITLE
Question about baseline

### ISSUE THREAD

**Issue by TinyAway** [syp2ysy/SVF#1]
Thanks for sharing your interesting work. I have a question when studying your paper. It is observed that you got better results using ASPP instead of FEM in PFENet as shown in Table 12. However, this phenomenon is opposite to the result in the original paper. Did you use any extra tricks to get these results?

**Comment by 930764657** [comment]
> Thanks for sharing your interesting work. I have a question when studying your paper. It is observed that you got better results using ASPP instead of FEM in PFENet as shown in Table 12. However, this phenomenon is opposite to the result in the original paper. Did you use any extra tricks to get these results?

I'm also a reader, but in table1/2, results using ASPP instead of FEM in PFENet is lower than using FEM, the data with + should be compared.

**Comment by syp2ysy** [comment]
@TinyAway Thanks for your interest. Some details in our code are different from original pfenet code,  for example, the batchnorm in the backbone needs to be adjusted to the _.eve()_ mode; using _DistributedDataParallel_ with _SyncBatchNorm_. In the same framework, pfenet performs much better than ASPP, fairer results are in table1 and table2. Following previous paper, the results of comparison methods in Table 12 were obtained directly from the original paper.
