### ISSUE TITLE
fss model

### ISSUE THREAD

**Issue by chenkeer37** [syp2ysy/SVF#10]
运行出现NameError: name 'FSS_model' is not defined     ;
code中有一处Layer写成Lyaer;

**Comment by syp2ysy** [comment]
@chenkeer37 非常感谢你指出我们的错误，我们已经对其进行了修正。该代码只是核心code，不能直接运行，运行方式参考readme.md。如果你需要torch的核心代码在https://github.com/zechao-li/SVF-pytorch， SVF在FSS上实验的code在https://github.com/zechao-li/SVF-few-shot-segmentation. 希望能给你带来帮助

**Comment by chenkeer37** [comment]
你好，{如果你需要torch的核心代码在 [https://github.com/zechao-li/SVF-pytorch]},page not found 404 ，是否在更新。

**Comment by chenkeer37** [comment]
> @chenkeer37非常感谢你指出我们的错误，我们已经对其进行了修正。该代码只是核心code，不能直接运行，运行方式参考 readme.md。如果你需要torch的核心代码在 [https://github.com/zechao-li/SVF-pytorch，](https://github.com/zechao-li/SVF-pytorch%EF%BC%8C)SVF在FSS上实验的code在 https://github.com/zechao-li/SVF-few-shot-segmentation.希望能给你带来帮助



> @chenkeer37非常感谢你指出我们的错误，我们已经对其进行了修正。该代码只是核心code，不能直接运行，运行方式参考 readme.md。如果你需要torch的核心代码在 [https://github.com/zechao-li/SVF-pytorch，](https://github.com/zechao-li/SVF-pytorch%EF%BC%8C)SVF在FSS上实验的code在 https://github.com/zechao-li/SVF-few-shot-segmentation.希望能给你带来帮助



> @chenkeer37非常感谢你指出我们的错误，我们已经对其进行了修正。该代码只是核心code，不能直接运行，运行方式参考 readme.md。如果你需要torch的核心代码在 [https://github.com/zechao-li/SVF-pytorch，](https://github.com/zechao-li/SVF-pytorch%EF%BC%8C)SVF在FSS上实验的code在 https://github.com/zechao-li/SVF-few-shot-segmentation.希望能给你带来帮助

你好，torch的核心代码404，可否重新公布一下，非常感谢。
