### ISSUE TITLE
Visualization in Fig. 4 and Fig.5

### ISSUE THREAD

**Issue by alpoler** [syp2ysy/SVF#12]
Hello,

"Next, we visualize the semantic cues of subspace U with the largest variation in singular values. The results are shown in Figure 4 and Figure 5". Could you, @syp2ysy, give detail about how to perform this visualization ?

**Comment by syp2ysy** [comment]
@alpoler 
After passing through the U subspace, the dimension of the resulting feature map is the same as that of the singular value vector. Thus, we visualize the feature map generated by U based on the index with the largest and smallest changes in the initial and final singular value vectors. 
Simply put, it means that we take two 1xHxW tensors from the feature map based on these two indices.
