### ISSUE TITLE
About baselines PFENet and PFENet\dagger

### ISSUE THREAD

**Issue by Sam1224** [syp2ysy/SVF#3]
Hi, thanks for your great work!
For your baselines, PFENet and PFENet\dagger,  could you please share some details about them? Because I could reproduce the results of PFENet, but when I replace the dataset as that of BAM (i.e., remove training samples with novel classes, while all other things remain the same), my obtained results are not as good as what you provide, e.g., 66.35% mIoU of PFENet\dagger (Res-50) provided in Table 1, while <64% in my experiments.

**Comment by Sam1224** [comment]
In Table. 10, PFENet-Res50-w/0 has mIoU of 63.34%, but the original one is 60.8%.

**Comment by syp2ysy** [comment]
@Sam1224 Thanks for your interest.  We reproduced PFENet in the BAM framework. The BAM framework has improved the original pfenet framework. For details, refer to BAM (https://github.com/chunbolang/BAM).

**Comment by Sam1224** [comment]
> @Sam1224 Thanks for your interest. We reproduced PFENet in the BAM framework. The BAM framework has improved the original pfenet framework. For details, refer to BAM (https://github.com/chunbolang/BAM).

Thanks for your reply. Is it correct that I just need to (1) drop the base learner and merge part of BAM? (2) replace the backbone as that of trained base learners of BAM?

**Comment by syp2ysy** [comment]
> > @Sam1224 Thanks for your interest. We reproduced PFENet in the BAM framework. The BAM framework has improved the original pfenet framework. For details, refer to BAM (https://github.com/chunbolang/BAM).
> 
> Thanks for your reply. Is it correct that I just need to (1) drop the base learner and merge part of BAM? (2) replace the backbone as that of trained base learners of BAM?

Yes, and you should be noted that the loss of pfenet is different from that of BAM.

**Comment by Sam1224** [comment]
> > > @Sam1224 Thanks for your interest. We reproduced PFENet in the BAM framework. The BAM framework has improved the original pfenet framework. For details, refer to BAM (https://github.com/chunbolang/BAM).
> > 
> > 
> > Thanks for your reply. Is it correct that I just need to (1) drop the base learner and merge part of BAM? (2) replace the backbone as that of trained base learners of BAM?
> 
> Yes, and you should be noted that the loss of pfenet is different from that of BAM.

Thanks a lot! I will close this issue now.

**Comment by zhouzi180** [comment]
@syp2ysy Hi, thanks for your great work! I found a typo in table 10 of the paper. The mIoU for PFENet-ResNet50-w/0 is 63.34%, not 66.34%.
