### ISSUE TITLE
Reimplement the svf method based on the PFENet code and the result is inferior than original PFENet.

### ISSUE THREAD

**Issue by lyphui** [syp2ysy/SVF#8]
Thanks for your nice work. I implement the svf method based on the PFENet code and the result is inferior than original PFENet. I followed the parameter setting in PFENet. And I used the same dataset and parameter setting in both **original PFENet** and **PFENet with SVF**. But the performance of PFENet with SVF performs worse than original PFENet. Could you please share your full-training code  rather than svf module code? Thanks a lot!

**Comment by YAOSL98** [comment]
I also met this question. I used SVF method in Meta-DETR (a few-shot detection method), and I decompose backbone layer3 and layer4. My results also decrease.

**Comment by syp2ysy** [comment]
@lyphui The reason for this is detailed in this issue _https://github.com/syp2ysy/SVF/issues/3_

**Comment by syp2ysy** [comment]
@YAOSL98 Sorry, we haven't tried it on the detection task yet. The exact reason may not be very clear. We will later verify the effectiveness of SVF in the detection task, and update the details on the homepage.
