### ISSUE TITLE
Quesitions about SVD

### ISSUE THREAD

**Issue by 1173206772** [syp2ysy/SVF#9]
Limited by my mathematical level, I don't know the specific meaning of _full_rank_ and _low_rank_ in the code. In other words, why do you set these two parameters, could you explain it to me, thank you

**Comment by 1173206772** [comment]
by the way，your work is great

**Comment by syp2ysy** [comment]
@1173206772 In this paper full_rank and low_rank are the same.
The ratio=1.0 in **_round_to_nearest_** means that full_rank and low_rank are the same, and when the ratio is less than 0, it means that the weights are compressed.
